---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back1
  labels:
    app: back1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back1
  template:
    metadata:
      labels:
        app: back1
    spec:
      containers:
      - name: nginx-back1
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: back1
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress-public"
spec:
  rules:
  - host: back1.kubernetes.local
    http:
      paths:
      - backend:
          serviceName: back1
          servicePort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: back1
spec:
  selector:
    app: back1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
