---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back2
  labels:
    app: back2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back2
  template:
    metadata:
      labels:
        app: back2
    spec:
      containers:
      - name: nginx-back2
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: back2
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress-secure"
spec:
  rules:
  - host: back2.kubernetes.local
    http:
      paths:
      - backend:
          serviceName: back2
          servicePort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: back2
spec:
  selector:
    app: back2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
